services:
  - type: web
    name: steady
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
